### PR TITLE
Added "Sea Curse", "Red Shadows" and "The Fearsome Touch of Death"

### PR DESCRIPTION
**Pull request by HendrikBK**
Three short stories by Robert E. Howard. I did my best to make everything right, but I'm not sure about some instances of words representing sounds and three instances of graphemes that might not entirely correct, so please give me feedback on that.

### CODE REVIEW

**Comment by acabal** [comment]
- Missing epigraph CSS: https://standardebooks.org/manual/1.8.0/single-page#7.4.5.2
- Missing `title` semantics in hgroups in Red Shadow https://standardebooks.org/manual/1.8.0/single-page#6.2.1.6.3
- Remove italics from Monsieur, that's English now
- `<i>Ha!</i> <i>ha!</i> <i>ha!</i> <i>ha!</i>` can just be one single `<i>` element, same with `<i>boom</i>, <i>boom</i>, <i>boom</i>` and `<i>thrum</i>, <i>throom</i>, <i>thrum</i>`
- You modernized `re-covered` in `he recovered his gray face` but that should remain as `re-covered` as the meaning is not the same

**Comment by acabal** [comment]
You'll have to rebuild the ToC after updating the titles in Red Shadows. Make sure to run se lint again too.

**Comment by HendrikBK** [comment]
I believe I fixed the mistakes. It was a good reminder about the words representing sounds, since I would like make the same mistake in my current production. The only issue in lint now is about the word-count in metadata.

**Comment by acabal** [comment]
OK, looks good, thanks!

**Pull request merged**
